replicaCount: 3

image:
  repository: 123456789012.dkr.ecr.us-east-1.amazonaws.com/java-app
  pullPolicy: Always
  tag: master #git master branch

serviceAccount:
  create: true
  name: java-app-sa

securityContext: 
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific

resources: 
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 10
  maxReplicas: 100
  targetCPUUtilizationPercentage: 40


nodeSelector: 
  fw-rapid : "dedicated"

tolerations: 
-   key: "dedicated"
    value:  "fw-rapid"
    effect: "NO_SCHEDULE"


