apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-private
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:gouthamik269/fw-test.git   
    targetRevision: main                              
    path: argo-applications/ingress-nginx-private     
    helm:
      chart: ingress-nginx
      repoURL: https://kubernetes.github.io/ingress-nginx
      version: 4.12.0
      releaseName: ingress-nginx-private
      valueFiles:
        - values.yaml                                 
  destination:
    server: https://<EKS-API-ENDPOINT>
    namespace: ingress-control
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

