controller:
  name: private
  replicaCount: 6
  ingressClass: private
  ingressClassResource:
    name: private
    default: false
    enabled: true
    controllerValue: "k8s.io/ingress-nginx-private"
  admissionWebhooks:
    enabled: false
  config:
    add-headers: "ingress-control/nginx-custom-security-headers"
    enable-vts-status: "true"
    proxy-body-size: "50m"
    server-tokens: "false"
    use-forwarded-headers: "true"
  service:
    ports:
      http: 80
      https: 443
    targetPorts:
      http: http
      https: http
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-internal: true
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: 900
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: tls_arn
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
  nodeSelector:
    ingress-control: dedicated
  tolerations:
    - key: dedicated
      value: ingress-control
  resources:
    requests:
      cpu: 300m
      memory: 192Mi
    limits:
      cpu: 1200m
      memory: 3Gi

